f_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('management.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
]

management/urls.py
from django.urls import path,re_path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'management'

urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.log_in, name='login'),
    path('logout/',views.log_out, name='logout'),
    path('register/',views.register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    path('accounts/password_reset/',auth_views.password_reset,name='password_reset'),
    path('accounts/password_reset/done/',auth_views.password_reset_done,name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.password_reset_confirm,name='password_reset_confirm'),
    path('accounts/reset/done/',auth_views.password_reset_complete,name='password_reset_complete'),
    path('password/',views.change_password, name='change_password'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('dashboard/createwishlist',views.createwishlist,name='createwishlist'),
    path('dashboard/deletewishlist/<int:wishlist_id>',views.deletewishlist,name='deletewishlist'),
    path('dashboard/createapplied',views.createapplied,name='createapplied'),
    path('dashboard/deleteapplied/<int:applied_id>',views.deleteapplied,name='deleteapplied'),
    path('dashboard/wishlistinfo/<int:wishlist_id>',views.wishlistinfo,name='wishlistinfo'),
    path('dashboard/appliedinfo/<int:applied_id>',views.appliedinfo,name='appliedinfo'),
    path('dashboard/tasks',views.tasks,name='tasks'),
    path('dashboard/createtask',views.createtask,name='createtask'),
    path('dashboard/completetask/<int:task_id>',views.completetask,name='completetask'),
    path('dashboard/deletecompleted',views.deletecompleted,name='deletecompleted'),
    path('dashboard/deletetask/<int:task_id>',views.deletetask,name='deletetask'),
    path('dashboard/jobactivity',views.jobactivity,name='jobactivity'),
    path('dashboard/chartdata',views.chartdata,name='chartdata'),
]

management/models.py
from django.db import models

from django.utils import timezone

from django.contrib.auth.models import User

import datetime

class Wishlist(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.CharField(max_length=200)
    job_title = models.CharField(max_length=200)
    deadline = models.DateField(null=True)
    applied = models.DateField('date applied',null=True)
    location = models.CharField(max_length=200,blank=True,default='')
    salary = models.IntegerField(null=True)
    post_url = models.URLField(max_length=2000,blank=True,default='')
    status = models.TextField(blank=True,default='')
    offer = models.DateField('offer date',null=True)
    
    def __str__(self):
        return self.company

    
class Applied(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.CharField(max_length=200)
    job_title = models.CharField(max_length=200)
    applied = models.DateField('date applied')
    deadline = models.DateField(null=True)
    location = models.CharField(max_length=200,blank=True,default='')
    salary = models.IntegerField(null=True)
    post_url = models.URLField(max_length=2000,blank=True,default='')
    status = models.TextField(blank=True,default='')
    offer = models.DateField('offer date',null=True)

    def __str__(self):
        return self.company

class Task(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100,blank=True,default='')
    text = models.TextField()
    complete = models.BooleanField(default=False)
    date = models.DateField('created date',null=True)

    def __str__(self):
        return self.text
    

management/forms.py
from django import forms
import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class WishListForm(forms.Form):
    company = forms.CharField(max_length=200)
    job_title = forms.CharField(max_length=200)

class AppliedForm(forms.Form):
    company = forms.CharField(max_length=200)
    job_title = forms.CharField(max_length=200)
    applied = forms.DateField(initial=datetime.date.today,widget=forms.DateInput(attrs={'type': 'date'}))

class JobInfoForm(forms.Form):
    company = forms.CharField(max_length=200)
    job_title = forms.CharField(max_length=200)
    applied = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}),required=False)
    deadline = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}),required=False)
    location = forms.CharField(max_length=200,required=False)
    salary = forms.IntegerField(required=False)
    post_url = forms.URLField(max_length=2000,required=False)
    status = forms.CharField(widget=forms.Textarea(),required=False)
    offer = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}),required=False)

class TaskForm(forms.Form):
    title = forms.CharField(max_length=100)
    text = forms.CharField(widget=forms.Textarea())
    date = forms.DateField(initial=datetime.date.today,widget=forms.DateInput(attrs={'type': 'date'}))

management/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm

from django.contrib.auth import login, authenticate,logout,update_session_auth_hash

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from django.urls import reverse

from django.forms import formset_factory,BaseFormSet

from django.contrib import messages

from django.conf import settings

from django.template.loader import render_to_string

from django.contrib.sites.shortcuts import get_current_site

from django.utils.encoding import force_bytes, force_text

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .tokens import account_activation_token

from django.core.mail import EmailMessage

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from datetime import datetime

from .forms import UserLoginForm,SignupForm,WishListForm,AppliedForm,JobInfoForm,TaskForm

from .models import Wishlist,Applied,Task

import requests


def home(request):
    if request.user.is_authenticated:
        return redirect('management:dashboard')
    
    return render(request, 'management/home.html')

def log_in(request):
    if request.user.is_authenticated:
        return redirect('management:dashboard')
    
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('management:dashboard')
            else:
                return render(request,'management/login.html',{'form' : form,'user' : user})
    else:
        form = UserLoginForm
    context = { 'form' : form }
    return render(request,'management/login.html', context)


def log_out(request):
    logout(request)
    return redirect('management:home')


def register(request):
    if request.user.is_authenticated:
        return redirect('management:dashboard')
    
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()

            if result['success']:
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your account.'
                message = render_to_string('management/acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                    'token':account_activation_token.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
                return HttpResponse('An activation Link has been sent to your email address.Please Check your Inbox')
            else:
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
    else:
        form = SignupForm()

    context = { 'form' : form }
    return render(request, 'management/register.html', context)


def activate(request, uidb64, token,backend='django.contrib.auth.backends.ModelBackend'):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        messages.success(request, 'Thank you for your email confirmation. Now you have logged In')
        return redirect('management:dashboard')
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('management:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'management/change_password.html', {'form': form})

@login_required(login_url='/login')
def dashboard(request):
    username = request.user
    wishlists = Wishlist.objects.filter(username=username)
    appliedlists = Applied.objects.filter(username=username)
    context = {
        'wishlists': wishlists,
        'appliedlists': appliedlists,
    }
    return render(request, 'management/dashboard.html',context)

@login_required(login_url='/login')
def createwishlist(request):
    if request.method == 'POST':
        wishform = WishListForm(request.POST)
        if wishform.is_valid():
            username = request.user
            wishlist = username.wishlist_set.create(company=request.POST['company'],job_title=request.POST['job_title'])
            return redirect('management:dashboard')
    else:
        wishform = WishListForm()
    context = { 'wishform' : wishform }
    return render(request,'management/createwishlist.html', context)

@login_required(login_url='/login')
def deletewishlist(request,wishlist_id):
    wishlist = get_object_or_404(Wishlist,pk=wishlist_id)
    wishlist.delete()
    return redirect('management:dashboard')

@login_required(login_url='/login')
def createapplied(request):
    if request.method == 'POST':
        appliedform = AppliedForm(request.POST)
        if appliedform.is_valid():
            username = request.user
            applied = username.applied_set.create(company=request.POST['company'],job_title=request.POST['job_title'],applied=request.POST['applied'])
            return redirect('management:dashboard')
    else:
        appliedform = AppliedForm()
    context = { 'appliedform' : appliedform }
    return render(request,'management/createapplied.html', context)

@login_required(login_url='/login')
def deleteapplied(request,applied_id):
    applied = get_object_or_404(Applied,pk=applied_id)
    applied.delete()
    return redirect('management:dashboard')

@login_required(login_url='/login')
def wishlistinfo(request,wishlist_id):
    if request.method == 'POST':
        form1 = JobInfoForm(request.POST)
        if form1.is_valid():
            wishlist_jobinfo = get_object_or_404(Wishlist,pk=wishlist_id)
            wishlist_jobinfo.company = request.POST['company']
            wishlist_jobinfo.job_title = request.POST['job_title']
            if(request.POST['deadline'] == ''):
                wishlist_jobinfo.deadline = None
            else:
                wishlist_jobinfo.deadline = request.POST['deadline']
            if(request.POST['applied'] == ''):
                wishlist_jobinfo.applied = None
            else:
                wishlist_jobinfo.applied = request.POST['applied']
            wishlist_jobinfo.location = request.POST['location']
            if(request.POST['salary'] == ''):
                wishlist_jobinfo.salary = None
            else:
                wishlist_jobinfo.salary = request.POST['salary']
            wishlist_jobinfo.post_url = request.POST['post_url']
            wishlist_jobinfo.status= request.POST['status']
            if(request.POST['offer'] == ''):
                wishlist_jobinfo.offer = None
            else:
                wishlist_jobinfo.offer = request.POST['offer']
            wishlist_jobinfo.save()
            return redirect('management:dashboard')
    else:
        wishlist_jobinfo = get_object_or_404(Wishlist,pk=wishlist_id)
        data={
            'company' : wishlist_jobinfo.company,
            'job_title' : wishlist_jobinfo.job_title,
            'deadline' : wishlist_jobinfo.deadline,
            'applied' : wishlist_jobinfo.applied,
            'location' : wishlist_jobinfo.location,
            'salary' : wishlist_jobinfo.salary,
            'post_url' : wishlist_jobinfo.post_url,
            'status' : wishlist_jobinfo.status,
            'offer' : wishlist_jobinfo.offer,
        }
        form1 = JobInfoForm(data)
    context = { 'form1' : form1 , 'wishlist_jobinfo' : wishlist_jobinfo}
    return render(request,'management/wishlistjobinfo.html',context)

@login_required(login_url='/login')
def appliedinfo(request,applied_id):
    if request.method == 'POST':
        form2 = JobInfoForm(request.POST)
        if form2.is_valid():
            applied_jobinfo = get_object_or_404(Applied,pk=applied_id)
            applied_jobinfo.company = request.POST['company']
            applied_jobinfo.job_title = request.POST['job_title']
            if(request.POST['deadline'] == ''):
                applied_jobinfo.deadline = None
            else:
                applied_jobinfo.deadline = request.POST['deadline']
            if(request.POST['applied'] == ''):

management/templates/management/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'management:activate' uidb64=uid token=token %}

Sincerely,
Job Tacker Team
{% endautoescape %}

management/templates/management/appliedjobinfo.html
{% load bootstrap4 %}   
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                 <div class="modal-header">
                        <h4 class="modal-title">JOB INFO</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                 <div class="modal-body">
                     <form method="POST" action ="{% url 'management:appliedinfo' applied_jobinfo.id %}">
                             {% csrf_token %}
                             <table>
                            {% bootstrap_form form2 layout='horizontal' %}
                             </table>
                 <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">SAVE CHANGES</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
                    </div>
                </div>
            </div>
        </div>

management/templates/management/change_password.html
{% extends 'management/dashboardlayout.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <br><br>
<div class="jumbotron">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h2>Change Password</h2>
<br>
<form method="post">
	<div class="form-group">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">Save changes</button>
  {% endbuttons %}
</div>
</form>
</div>
</div>
{% endblock %}

management/templates/management/createapplied.html
{% load bootstrap4 %}   
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                 <div class="modal-header">
                        <h4 class="modal-title">ADD APPLIED</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                 <div class="modal-body">
                     <form method="POST" action ="{% url 'management:createapplied' %}">
                             {% csrf_token %}
                             <table>
                            {% bootstrap_form appliedform %}
                             </table>
                 <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">ADD</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
                    </div>
                </div>
            </div>
        </div>

management/templates/management/createtask.html
{% load bootstrap4 %}   
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                 <div class="modal-header">
                        <h4 class="modal-title">ADD TASK</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                 <div class="modal-body">
                     <form method="POST" action ="{% url 'management:createtask' %}">
                             {% csrf_token %}
                             <table>
                            {% bootstrap_form taskform %}
                             </table>
                 <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">ADD</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
                    </div>
                </div>
            </div>
        </div>

management/templates/management/createwishlist.html
{% load bootstrap4 %}   
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                 <div class="modal-header">
                        <h4 class="modal-title">ADD WISHLIST</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                 <div class="modal-body">
                     <form id="form1" method="POST" action ="{% url 'management:createwishlist' %}">
                             {% csrf_token %}
                             <table>
                            {% bootstrap_form wishform %}
                             </table>
                 <div class="modal-footer">
                        <button id="formsubmit" type="submit" class="btn btn-primary">ADD</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
                    </div>
                </div>
            </div>
        </div>

management/templates/management/dashboard.html
{% extends 'management/dashboardlayout.html' %}
{% block content %}
<div class="container">
  <br>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <button type="button" id="cbutton" class="btn btn-primary" data-toggle="modal" data-target="#basicModal" ><i class="fas fa-plus"></i> ADD WISHLIST</button>
    <div class="modal" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModalTitle" aria-hidden="true">
    </div>
    &nbsp;&nbsp;&nbsp;
    <button type="button" id="appliedbutton" class="btn btn-primary" data-toggle="modal" data-target="#appliedModal" ><i class="fas fa-plus"></i> ADD APPLIED</button>
    <div class="modal" id="appliedModal" tabindex="-1" role="dialog" aria-labelledby="appliedModalTitle" aria-hidden="true">
    </div>
    <br><br>
<div class="jumbotron">

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="wishlist-tab" data-toggle="tab" href="#wishlist" role="tab" aria-controls="wishlist" aria-selected="true"><i class="fas fa-magic"></i> WishList</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><i class="fas fa-file-alt"></i> Applied</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="wishlist" role="tabpanel" aria-labelledby="wishlist-tab">
      <br>
        <div class="row">
                {% for wishlist in wishlists %}
                <div class="col-sm-4">
                  <div class="card mt-3">
                      <div class="card-header">
                        <h5 class="card-title">{{ wishlist.company }}</h5>
                      </div>
                    <div class="card-body">
                      <p class="card-text">{{ wishlist.job_title }}</p>
                      {% if wishlist.deadline %}
                      <p class="card-text">Deadline: {{ wishlist.deadline }}</p>
                      {% else %}
                      {% endif %}
                      {% if wishlist.status %}
                      <p class="card-text">Status: {{ wishlist.status }}</p>
                      {% else %}
                      {% endif %}
                      </div>
                      <div class="card-footer">
                      <button onclick="wishinfofunc('{{wishlist.id}}')" type="button" id="wishinfobutton" class="btn btn-primary" data-toggle="modal" data-target="#wishinfoModal" ><i class="fas fa-info-circle"></i> JOB INFO</button>
                      <div class="modal" id="wishinfoModal" tabindex="-1" role="dialog" aria-labelledby="wishinfoModalTitle" aria-hidden="true">
                      </div>
                      <a href="{% url 'management:deletewishlist' wishlist.id %}" class="btn btn-secondary float-right" onclick="return confirm('Are you sure you want to Delete?');"><i class="fas fa-trash-alt"></i> DELETE</a>
                    </div>
                  </div>
                </div>
            {% endfor %}
            </div>                        
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <br>
        <div class="row">
                {% for appliedlist in appliedlists %}
                <div class="col-sm-4">
                  <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">{{ appliedlist.company }}</h5>
                    </div>
                    <div class="card-body">
                      <p class="card-text">{{ appliedlist.job_title }}</p>
                      <p class="card-text">Applied On: {{ appliedlist.applied }}</p>
                      {% if appliedlist.status %}
                      <p class="card-text">Status: {{ appliedlist.status }}</p>
                      {% else %}
                      {% endif %}
                      </div>
                      <div class="card-footer">
                      <button onclick="appliedinfofunc('{{appliedlist.id}}')" type="button" id="appliedinfobutton" class="btn btn-primary" data-toggle="modal" data-target="#appliedinfoModal" ><i class="fas fa-info-circle"></i> JOB INFO</button>
                      <div class="modal" id="appliedinfoModal" tabindex="-1" role="dialog" aria-labelledby="appliedinfoModalTitle" aria-hidden="true">
                      </div>
                      <a href="{% url 'management:deleteapplied' appliedlist.id %}" class="btn btn-secondary float-right" onclick="return confirm('Are you sure you want to Delete?');"><i class="fas fa-trash-alt"></i> DELETE</a>
                    </div>
                  </div>
                </div>
            {% endfor %}
            </div>                        
  </div>
</div>
      </div>
      </div>
{% endblock %}

management/templates/management/home.html
{% extends 'management/layout.html' %}
{% block content %}
{% load staticfiles %}
<body style="background-image: url('{% static "management/img/Elegant_Background-8.jpg" %}');"></body>
<br><br>
<img class="img center" src="{% static 'management/img/jobs.png' %}" alt="profile" height="400">
<br>
<center><h1 class="text-uppercase" style="color:white;">"TRACK YOUR JOBS NOW"</h1></center>
<br>
<hr class="star-light"><br>
<center><a class="btn btn-primary frontbutton btn-xl text-uppercase js-scroll-trigger" href="{% url 'management:register' %}">GET STARTED</a></center>
{% endblock %}

management/templates/management/login.html
{% extends 'management/layout.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="container">
<div class="jumbotron">
<div class="container">
{% if user == None %}
{% bootstrap_alert "Your username and password didn't match." alert_type='error' dismissable=True %}
{% endif %}
  <h2>Login</h2>
  <br>
  <form method="POST" action ="{% url 'management:login' %}" >
    <div class="form-group">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    {% buttons %}
    <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
<br>
<a href= "{% url 'management:register' %}">Not yet registered?Sign Up</a>
<br><br>
<a href= "{% url 'management:password_reset' %}">Forgot your password?</a>
    </div>
  </form>
</div></div>
</div>
{% endblock %}

management/templates/management/register.html
{% extends 'management/layout.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
<div class="jumbotron">
<div class="container">
  <h2>Sign up</h2>
  <br>
  <form method="POST">
    <div class="form-group">
    {% csrf_token %}
    {% bootstrap_form form %}

    <br>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <div class="g-recaptcha" data-sitekey="6Lfce1kUAAAAAC29O4mm-yE9tKqj11MnUsWfTWdT"></div>
    <br>

    {% buttons %}
    <button type="submit" class="btn btn-primary">Sign up</button>
    {% endbuttons %}
    </div>
  </form>
</div></div>
</div>
{% endblock %}

management/templates/management/tasks.html
{% extends 'management/dashboardlayout.html' %}
{% block content %}
<div class="container">
    <br><br>
    <button type="button" id="taskbutton" class="btn btn-primary" data-toggle="modal" data-target="#taskModal" ><i class="fas fa-plus"></i> ADD TASKS</button>
    <div class="modal" id="taskModal" tabindex="-1" role="dialog" aria-labelledby="taskModalTitle" aria-hidden="true">
    </div>
    &nbsp;&nbsp;
    <a href="{% url 'management:deletecompleted' %}" class="btn btn-secondary" onclick="return confirm('Are you sure you want to Delete?');"><i class="fas fa-trash-alt"></i> DELETE COMPLETED TASKS</a>
    <br><br>
<div class="jumbotron">
        <div class="row">
                {% for task in tasks %}
                <div class="col-sm-4">
                <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="card-header">
                <h5>{{task.title}}</h5>
                </div>
                <div class="card-body">
                <p class="card-text">{{ task.text }}</p>
                <p class="card-text">Added On: {{ task.date }}</p>
                </div>
                <div class="card-footer">
                    {% if task.complete %}
                    <p class="inline">COMPLETED</p>
                    {% else %}
                    <a href="{% url 'management:completetask' task.id %}" class="btn btn-primary inline">COMPLETE</a>
                    {% endif %}
                    <a href="{% url 'management:deletetask' task.id %}" class="btn btn-secondary float-right" onclick="return confirm('Are you sure you want to Delete?');">DELETE</a>
                </div>
            </div>
        </div>
{% endfor %}
</div>
 </div>         
{% endblock %}              

management/templates/management/wishlistjobinfo.html
{% load bootstrap4 %}   
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                 <div class="modal-header">
                        <h4 class="modal-title">JOB INFO</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                 <div class="modal-body">
                     <form method="POST" action ="{% url 'management:wishlistinfo' wishlist_jobinfo.id %}">
                             {% csrf_token %}
                             <table>
                            {% bootstrap_form form1 layout='horizontal' %}
                             </table>
                 <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">SAVE CHANGES</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
                    </div>
                </div>
            </div>
        </div>